development:
  adapter: sqlserver
  dsn: gym-cc
  mode: odbc
  database: CountryClubSQL

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gymcc_staging
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: sqlserver
  dsn: gym-cc
  mode: odbc
  database: CountryClubSQL
